version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install
      - echo Installing AWS CLI...
      - apt-get update && apt-get install -y awscli
      - echo Installing Docker...
      - apt-get update && apt-get install -y docker.io
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo repo --- $REPOSITORY_URI
      - docker --version
      - aws --version
      - echo $(aws ecr get-login-password --region $AWS_DEFAULT_REGION)
      - echo $(docker login --username AWS --password-stdin $REPOSITORY_URI)
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Writing image definitions file...
      - printf '[{"name":"frontend-repo","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json

artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
